from __future__ import annotations

from enum import StrEnum


class AssetType(StrEnum):
    LISTED_EQUITY = "LISTED_EQUITY"


class TransactionType(StrEnum):
    BUY = "BUY"
    SELL = "SELL"
    DIVIDEND = "DIVIDEND"
    DEPOSIT = "DEPOSIT"
    WITHDRAWAL = "WITHDRAWAL"
    FEE = "FEE"
    TAX = "TAX"
    STOCK_SPLIT = "STOCK_SPLIT"
    BONUS_ISSUE = "BONUS_ISSUE"
    SECURITY_IDENTIFIER_CHANGE = "SECURITY_IDENTIFIER_CHANGE"
    REVERSAL = "REVERSAL"
    AMENDMENT = "AMENDMENT"


class TransactionStatus(StrEnum):
    POSTED = "POSTED"
    REVERSED = "REVERSED"


class ImportType(StrEnum):
    TRANSACTIONS = "TRANSACTIONS"
    OPENING_POSITIONS = "OPENING_POSITIONS"


class ImportStatus(StrEnum):
    STAGED = "STAGED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    READY_FOR_CONFIRMATION = "READY_FOR_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"
    CORRECTED = "CORRECTED"


class ImportRowStatus(StrEnum):
    VALID = "VALID"
    REJECTED = "REJECTED"
    AMBIGUOUS_SECURITY = "AMBIGUOUS_SECURITY"
    UNRESOLVED_SECURITY = "UNRESOLVED_SECURITY"
    CONFIRMED = "CONFIRMED"


class CorporateActionType(StrEnum):
    STOCK_SPLIT = "STOCK_SPLIT"
    BONUS_ISSUE = "BONUS_ISSUE"
    SECURITY_IDENTIFIER_CHANGE = "SECURITY_IDENTIFIER_CHANGE"
    REVERSE_SPLIT = "REVERSE_SPLIT"
    RIGHTS_ISSUE = "RIGHTS_ISSUE"
    MERGER = "MERGER"
    SPIN_OFF = "SPIN_OFF"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    BLOCKED_STALE = "BLOCKED_STALE"
    FAILED = "FAILED"
