"""create core portfolio foundation schema

Revision ID: 5099b36d44f1
Revises: 
Create Date: 2026-08-14 17:04:44.906807

"""
from alembic import op
import sqlalchemy as sa


revision = '5099b36d44f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('broker', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'observed_at', 'provider', name='uq_fx_observation')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('logical_as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'BLOCKED_STALE', 'FAILED', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness', sa.JSON(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_job_idempotency_key')
    )
    op.create_table('llm_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_type', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('structured_output', sa.JSON(), nullable=False),
    sa.Column('evidence_references', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('report_timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('securities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('legal_name', sa.String(length=500), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('asset_type', sa.Enum('LISTED_EQUITY', name='assettype', native_enum=False), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_security_id'), 'events', ['security_id'], unique=False)
    op.create_table('fundamentals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundamentals_security_id'), 'fundamentals', ['security_id'], unique=False)
    op.create_table('investment_theses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('thesis_text', sa.Text(), nullable=False),
    sa.Column('structured_claims', sa.JSON(), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_theses_security_id'), 'investment_theses', ['security_id'], unique=False)
    op.create_table('portfolio_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('broker', sa.String(length=200), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'name', name='uq_account_name_per_portfolio')
    )
    op.create_index(op.f('ix_portfolio_accounts_portfolio_id'), 'portfolio_accounts', ['portfolio_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('cash_value', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('realised_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('unrealised_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('calculation_version', sa.String(length=100), nullable=False),
    sa.Column('source_versions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_portfolio_id'), 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('source_versions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_portfolio_id'), 'reports', ['portfolio_id'], unique=False)
    op.create_table('security_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.String(length=64), nullable=False),
    sa.Column('mic', sa.String(length=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'exchange', 'active_from', name='uq_listing_ticker_exchange_active')
    )
    op.create_index('ix_listing_ticker_exchange', 'security_listings', ['ticker', 'exchange'], unique=False)
    op.create_index(op.f('ix_security_listings_security_id'), 'security_listings', ['security_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=True),
    sa.Column('security_id', sa.String(length=36), nullable=True),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('observed_value', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('baseline_value', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('configuration_version', sa.String(length=100), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_portfolio_id'), 'signals', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_signals_security_id'), 'signals', ['security_id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['security_listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'listing_id', name='uq_holding_account_listing')
    )
    op.create_index(op.f('ix_holdings_account_id'), 'holdings', ['account_id'], unique=False)
    op.create_table('imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('import_type', sa.Enum('TRANSACTIONS', 'OPENING_POSITIONS', name='importtype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('STAGED', 'VALIDATION_FAILED', 'READY_FOR_CONFIRMATION', 'CONFIRMED', 'CANCELLED', 'CORRECTED', name='importstatus', native_enum=False), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mapping_version', sa.String(length=100), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('reconciliation_summary', sa.JSON(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('corrected_by_import_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['corrected_by_import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_account_content_hash', 'imports', ['account_id', 'content_hash'], unique=False)
    op.create_index(op.f('ix_imports_account_id'), 'imports', ['account_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('high', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('low', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('close', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('volume', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['security_listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'observed_at', 'provider', name='uq_price_observation')
    )
    op.create_index(op.f('ix_price_history_listing_id'), 'price_history', ['listing_id'], unique=False)
    op.create_table('holding_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('cost_basis', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('realised_pnl_to_date', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('unrealised_pnl', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('price_observation_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['security_listings.id'], ),
    sa.ForeignKeyConstraint(['price_observation_id'], ['price_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holding_snapshots_account_id'), 'holding_snapshots', ['account_id'], unique=False)
    op.create_table('import_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('normalized_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'REJECTED', 'AMBIGUOUS_SECURITY', 'UNRESOLVED_SECURITY', 'CONFIRMED', name='importrowstatus', native_enum=False), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('security_listing_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.ForeignKeyConstraint(['security_listing_id'], ['security_listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'row_number', name='uq_import_row_number')
    )
    op.create_index(op.f('ix_import_rows_import_id'), 'import_rows', ['import_id'], unique=False)
    op.create_table('opening_cash_balances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'currency', name='uq_opening_cash_currency')
    )
    op.create_index(op.f('ix_opening_cash_balances_account_id'), 'opening_cash_balances', ['account_id'], unique=False)
    op.create_index(op.f('ix_opening_cash_balances_import_id'), 'opening_cash_balances', ['import_id'], unique=False)
    op.create_table('opening_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('total_cost_basis', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('acquisition_date_unknown', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['security_listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'listing_id', name='uq_opening_position_listing')
    )
    op.create_index(op.f('ix_opening_positions_account_id'), 'opening_positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_opening_positions_import_id'), 'opening_positions', ['import_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('import_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'DEPOSIT', 'WITHDRAWAL', 'FEE', 'TAX', 'STOCK_SPLIT', 'BONUS_ISSUE', 'SECURITY_IDENTIFIER_CHANGE', 'REVERSAL', 'AMENDMENT', name='transactiontype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('POSTED', 'REVERSED', name='transactionstatus', native_enum=False), nullable=False),
    sa.Column('transaction_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_sequence', sa.Integer(), nullable=False),
    sa.Column('settlement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('tax', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate_to_base', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('external_reference', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('correction_of_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fees >= 0', name='ck_transaction_fees_nonnegative'),
    sa.CheckConstraint('quantity IS NULL OR quantity >= 0', name='ck_transaction_quantity_nonnegative'),
    sa.CheckConstraint('tax >= 0', name='ck_transaction_tax_nonnegative'),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['correction_of_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['security_listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'transaction_at', 'effective_sequence', name='uq_transaction_effective_order')
    )
    op.create_index('ix_transaction_account_effective', 'transactions', ['account_id', 'transaction_at'], unique=False)
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_import_id'), 'transactions', ['import_id'], unique=False)
    op.create_table('cash_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('opening_cash_balance_id', sa.String(length=36), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('entry_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['opening_cash_balance_id'], ['opening_cash_balances.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('ix_cash_account_date', 'cash_ledger', ['account_id', 'effective_at'], unique=False)
    op.create_index(op.f('ix_cash_ledger_account_id'), 'cash_ledger', ['account_id'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.Enum('STOCK_SPLIT', 'BONUS_ISSUE', 'SECURITY_IDENTIFIER_CHANGE', 'REVERSE_SPLIT', 'RIGHTS_ISSUE', 'MERGER', 'SPIN_OFF', name='corporateactiontype', native_enum=False), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ratio_numerator', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('ratio_denominator', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('successor_listing_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('terms', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['security_listings.id'], ),
    sa.ForeignKeyConstraint(['successor_listing_id'], ['security_listings.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_corporate_actions_account_id'), 'corporate_actions', ['account_id'], unique=False)
    op.create_table('lots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('originating_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('opening_position_id', sa.String(length=36), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_date_unknown', sa.Boolean(), nullable=False),
    sa.Column('fifo_sort_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fifo_sequence', sa.Integer(), nullable=False),
    sa.Column('original_quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit_cost_base', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('original_quantity >= 0', name='ck_lot_original_quantity_nonnegative'),
    sa.CheckConstraint('remaining_quantity >= 0', name='ck_lot_remaining_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['security_listings.id'], ),
    sa.ForeignKeyConstraint(['opening_position_id'], ['opening_positions.id'], ),
    sa.ForeignKeyConstraint(['originating_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lot_fifo', 'lots', ['account_id', 'listing_id', 'fifo_sort_at', 'fifo_sequence'], unique=False)
    op.create_index(op.f('ix_lots_account_id'), 'lots', ['account_id'], unique=False)
    op.create_index(op.f('ix_lots_listing_id'), 'lots', ['listing_id'], unique=False)
    op.create_table('lot_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sale_transaction_id', sa.String(length=36), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('allocated_cost', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('allocated_proceeds', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('realised_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['sale_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_transaction_id', 'lot_id', name='uq_sale_lot_allocation')
    )
    op.create_index(op.f('ix_lot_allocations_lot_id'), 'lot_allocations', ['lot_id'], unique=False)
    op.create_index(op.f('ix_lot_allocations_sale_transaction_id'), 'lot_allocations', ['sale_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_allocations_sale_transaction_id'), table_name='lot_allocations')
    op.drop_index(op.f('ix_lot_allocations_lot_id'), table_name='lot_allocations')
    op.drop_table('lot_allocations')
    op.drop_index(op.f('ix_lots_listing_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_account_id'), table_name='lots')
    op.drop_index('ix_lot_fifo', table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_corporate_actions_account_id'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_cash_ledger_account_id'), table_name='cash_ledger')
    op.drop_index('ix_cash_account_date', table_name='cash_ledger')
    op.drop_table('cash_ledger')
    op.drop_index(op.f('ix_transactions_import_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_index('ix_transaction_account_effective', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_opening_positions_import_id'), table_name='opening_positions')
    op.drop_index(op.f('ix_opening_positions_account_id'), table_name='opening_positions')
    op.drop_table('opening_positions')
    op.drop_index(op.f('ix_opening_cash_balances_import_id'), table_name='opening_cash_balances')
    op.drop_index(op.f('ix_opening_cash_balances_account_id'), table_name='opening_cash_balances')
    op.drop_table('opening_cash_balances')
    op.drop_index(op.f('ix_import_rows_import_id'), table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_holding_snapshots_account_id'), table_name='holding_snapshots')
    op.drop_table('holding_snapshots')
    op.drop_index(op.f('ix_price_history_listing_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_imports_account_id'), table_name='imports')
    op.drop_index('ix_import_account_content_hash', table_name='imports')
    op.drop_table('imports')
    op.drop_index(op.f('ix_holdings_account_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_signals_security_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_portfolio_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_security_listings_security_id'), table_name='security_listings')
    op.drop_index('ix_listing_ticker_exchange', table_name='security_listings')
    op.drop_table('security_listings')
    op.drop_index(op.f('ix_reports_portfolio_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_portfolio_snapshots_portfolio_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_accounts_portfolio_id'), table_name='portfolio_accounts')
    op.drop_table('portfolio_accounts')
    op.drop_index(op.f('ix_investment_theses_security_id'), table_name='investment_theses')
    op.drop_table('investment_theses')
    op.drop_index(op.f('ix_fundamentals_security_id'), table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index(op.f('ix_events_security_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('securities')
    op.drop_table('portfolios')
    op.drop_table('llm_assessments')
    op.drop_table('job_runs')
    op.drop_table('fx_history')
    op.drop_table('broker_mappings')
    # ### end Alembic commands ###
